workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

stages:
  - triggers

trigger-build-mate:
  stage: triggers
  trigger:
    include: ci/build-mate.yml
    strategy: depend

trigger-build-xfce:
  stage: triggers
  trigger:
    include: ci/build-xfce.yml
    strategy: depend