[colors.primary]
background = '#141312'
foreground = '#e6e2df'

[colors.cursor]
text = '#141312'
cursor = '#e6e2df'

[colors.vi_mode_cursor]
text = '#141312'
cursor = '#cdc6b2'

[colors.search.matches]
foreground = '#49473e'
background = '#c3c9bb'

[colors.search.focused_match]
foreground = '#49473e'
background = '#cdc6b2'

[colors.footer_bar]
foreground = '#49473e'
background = '#e6e2df'

[colors.hints.start]
foreground = '#49473e'
background = '#cbc6bc'

[colors.hints.end]
foreground = '#49473e'
background = '#cbc6bc'

[colors.selection]
text = '#cbc6bb'
background = '#49473e'


[colors.normal]
black   = '#49473e'
red     = '#ffb4ab'
green   = '#cdc6b2'
yellow  = '#cbc6bc'
blue    = '#c3c9bb'
magenta = '#cdc6b2'
cyan    = '#cbc6bc'
white   = '#e6e2df'


[colors.bright]
black   = '#959086'
red     = '#ffb4ab'
green   = '#cdc6b2'
yellow  = '#cbc6bc'
blue    = '#c3c9bb'
magenta = '#cdc6b2'
cyan    = '#cbc6bc'
white   = '#e6e2df'


[colors.dim]
black   = '#49473e'
red     = '#ffb4ab'
green   = '#cdc6b2'
yellow  = '#cbc6bc'
blue    = '#c3c9bb'
magenta = '#cdc6b2'
cyan    = '#cbc6bc'
white   = '#e6e2df'
