color0 #49473e
color1 #ffb4ab
color2 #cdc6b2
color3 #cbc6bc
color4 #c3c9bb
color5 #cdc6b2
color6 #cbc6bc
color7 #e6e2df
color8 #959086
color9 #ffb4ab
color10 #cdc6b2
color11 #cbc6bc
color12 #c3c9bb
color13 #cdc6b2
color14 #cbc6bc
color15 #e6e2df

cursor                #e6e2df
cursor_text_color     #141312
background            #141312
foreground            #e6e2df
selection_foreground  #cbc6bb
selection_background  #49473e
active_border_color   #cdc6b2
inactive_border_color #49473e
url_color             #cdc6b2

active_tab_foreground   #343022
active_tab_background   #cdc6b2
inactive_tab_foreground #cbc6bb
inactive_tab_background #49473e
cursor_trail_color      #cbc6bb
