color0 #1e2320
color1 #c27979
color2 #8da383
color3 #cb9b7c
color4 #728a96
color5 #a48fa1
color6 #7a998d
color7 #d3cdc3
color8 #47524b
color9 #d48f8f
color10 #a1b598
color11 #dbb095
color12 #8da3b0
color13 #baa9b8
color14 #93ad1a
color15 #e4dfd5

cursor                #d3cdc3
cursor_text_color     #1e2320
background            #1e2320
foreground            #d3cdc3
selection_foreground  #1e2320
selection_background  #8da383
active_border_color   #8da383
inactive_border_color #272e2a
url_color             #8da383

active_tab_foreground   #1e2320
active_tab_background   #8da383
inactive_tab_foreground #9da49a
inactive_tab_background #272e2a
cursor_trail_color      #9da49a
