name: Neko Void - Build All Chain

on:
  workflow_dispatch:

jobs:
  build-ice-jwm:
    uses: ./.github/workflows/ice-jwm.yml
    secrets: inherit # Hereda automáticamente todos los secretos (incluido el TOKEN)

  build-kde:
    needs: build-ice-jwm
    uses: ./.github/workflows/kde.yml
    secrets: inherit

  build-lxqt:
    needs: build-kde
    uses: ./.github/workflows/lxqt.yml
    secrets: inherit

  build-matelibre:
    needs: build-lxqt
    uses: ./.github/workflows/matelibre.yml
    secrets: inherit

  build-matex:
    needs: build-matelibre
    uses: ./.github/workflows/matex.yml
    secrets: inherit

  build-xfce:
    needs: build-matex
    uses: ./.github/workflows/xfce.yml
    secrets: inherit
  build-i3:
    needs: build-xfce
    uses: ./.github/workflows/i3.yml
    secrets: inherit
  