name: nvidia-Build Neko Void ISO KDE

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-neko-void:
    name: Build ISOs
    runs-on: ubuntu-latest

    container:
      image: 'ghcr.io/void-linux/void-mklive:20250116R1'
      options: --privileged
      volumes:
        - /dev:/dev
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'

    steps:
      - name: Prepare container, system users and dependencies
        shell: sh
        run: |
          xbps-install -Syu --repository=https://repo-de.voidlinux.org/current/  xbps
          xbps-install -yu --repository=https://repo-de.voidlinux.org/current/ 
          xbps-install -y --repository=https://repo-de.voidlinux.org/current/  git bash wget curl file sudo python3 python3-pip rsync openssh
          python3 -m pip install -U "huggingface_hub[cli]" --break-system-packages

          groupadd -g 1000 anon
          useradd -m -u 1000 -g anon -s /bin/bash anon
          echo "anon ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/anon

      - name: Clone Neko Void repository
        run: |
          mkdir -p /home/anon/workspace
          chown -R anon:anon /home/anon/workspace
          su - anon -c "git clone --depth 1 https://codeberg.org/Neko-Void/Build-Neko.git /home/anon/workspace"

      - name: Build Neko-Void ISO Xorg
        run: |
          cd /home/anon/workspace/live-maker
          rm -rf kdedir/etc/default/grub
          #Grub Custom
          wget -O kdedir/etc/default/grub https://huggingface.co/datasets/arepaconcafe/untested-neko/resolve/main/grub
          
          # Forzar que dracut incluya el módulo nvidia en la initramfs
          mkdir -p kdedir/etc/dracut.conf.d
          cat << 'EOFDRACUT' > kdedir/etc/dracut.conf.d/nvidia.conf
          # Incluir los módulos esenciales de NVIDIA en el initramfs
          add_drivers+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm "
          EOFDRACUT
          chmod 644 kdedir/etc/dracut.conf.d/nvidia.conf
          # Forzar carga de nvidia al inicio
          mkdir -p kdedir/etc/modules-load.d
          echo "nvidia" > kdedir/etc/modules-load.d/nvidia.conf

          rm -f ./includedir/home/anon/.Xauthority
          rm -f ./includedir/home/anon/.ICEauthority

          chmod 1777 /tmp
          chmod 1777 /var/tmp

          # Compilación real de la ISO
          bash neko-builder.sh kde -e "nvidia linux-headers nvidia-libs-32bit"

      - name: Generate Checksums
        run: |
          cd /home/anon/workspace
          sha256sum **/*.iso > sha256sum.txt || true

      - name: Upload ISO to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          ISO_FILE=$(find /home/anon/workspace -name "*.iso" | head -n 1)
          ISO_NAME=$(basename "$ISO_FILE")

          hf upload arepaconcafe/untested-neko "$ISO_FILE" "nvidia580-$ISO_NAME" --repo-type dataset --token $HF_TOKEN
          hf upload arepaconcafe/untested-neko /home/anon/workspace/sha256sum.txt "kde-sha256.txt" --repo-type dataset --token $HF_TOKEN