name: Build Neko Void ISO XORG (MATE)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-neko-void:
    name: Build ISOs
    runs-on: ubuntu-latest
    
    container:
      image: 'ghcr.io/void-linux/void-mklive:20250116R1'
      options: --privileged
      volumes:
        - /dev:/dev
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'

    steps:
      - name: Prepare container and dependencies
        shell: sh
        run: |
          xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y git bash wget curl file sudo python3 python3-pip
          python3 -m pip install -U "huggingface_hub[cli]" --break-system-packages

      - name: Clone Neko Void repository
        run: git clone https://codeberg.org/javiercplus/Neko-Void.git workspace

      - name: Build Neko-Void ISO Xorg
        run: |
          cd workspace/live-maker
          # 1. Hacer que todo pertenezca a root por defecto
          chown -R root:root includedir
          
          # 2. Permisos seguros para carpetas (755) y archivos (644)
          find includedir -type d -exec chmod 755 {} \;
          find includedir -type f -exec chmod 644 {} \;
          
          # 3. Restaurar permisos de ejecución para scripts (runit, ejecutables, etc.)
          find includedir -type f -name "run" -exec chmod +x {} \;
          find includedir -type f -name "*.sh" -exec chmod +x {} \;
          
          # 4. LA CLAVE: Devolverle la propiedad de su carpeta personal al usuario 'anon' (UID 1000 y GID 1000)
          if [ -d "./includedir/home/anon" ]; then
            chmod 755 ./includedir/home/anon
            chown -R 1000:1000 ./includedir/home/anon
          fi
          bash neko-builder.sh rolling
          

      - name: Build Neko-Void ISO XLIBRE
        run: |
          cd workspace/live-maker
          #bash neko-builder.sh rollinglibre
          echo "skip Xlibre"
      - name: Generate Checksums
        run: |
          cd workspace
          sha256sum **/*.iso > sha256sum.txt || true

      - name: Upload ISO to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          ISO_FILE=$(find workspace -name "*.iso" | head -n 1)
          ISO_NAME=$(basename "$ISO_FILE")
          
          hf upload arepaconcafe/untested-neko  "$ISO_FILE" "$ISO_NAME" --repo-type dataset --token $HF_TOKEN
          hf upload arepaconcafe/untested-neko  workspace/sha256sum.txt "sha256sum.txt" --repo-type dataset --token $HF_TOKEN

#      - name: Upload ISO Artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: neko-void-rolling-isos
#           path: |
#             workspace/**/*.iso
#             workspace/sha256sum.txt
#          if-no-files-found: error