color0 #474554
color1 #ffb4ab
color2 #c7bfff
color3 #c7bffe
color4 #ffabf0
color5 #c7bfff
color6 #c7bffe
color7 #e5e0ec
color8 #928ea0
color9 #ffb4ab
color10 #c7bfff
color11 #c7bffe
color12 #ffabf0
color13 #c7bfff
color14 #c7bffe
color15 #e5e0ec

cursor                #e5e0ec
cursor_text_color     #13121a
background            #13121a
foreground            #e5e0ec
selection_foreground  #c8c4d6
selection_background  #474554
active_border_color   #c7bfff
inactive_border_color #474554
url_color             #c7bfff

active_tab_foreground   #29009f
active_tab_background   #c7bfff
inactive_tab_foreground #c8c4d6
inactive_tab_background #474554
cursor_trail_color      #c8c4d6
